import './globals.css'

async function RootLayout({children}) {
    return (
        <html lang="en" className="h-full">
        <head>
            <title>MEHH Meedia UÜ</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </head>
        <body className="h-full flex">
            <main className="flex xl:items-center flex-1 bg-cover bg-bottom bg-[url('/slider-1.svg')]">
                <div className='max-w-7xl px-4 py-10 xl:px-32 flex-1'>
                    {children}
                </div>
            </main>
        </body>
        </html>
    )
}

export default RootLayout