import './globals.css'
import client from "../utils/fetch/client";
import Header from "../components/layout/header";

async function RootLayout({children}) {
    const menu = await client('wp/v2/menu')

    // console.log('menu2', menu)

    return (
        <html lang="en" className="h-full">
        <head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </head>
        <body className="h-full flex flex-col">
            <Header menu={menu}/>
            <main className="flex-1">
                <div className='mx-auto max-w-7xl my-12 px-2 sm:px-6 lg:px-8'>
                    {children}
                </div>
            </main>
            <footer className="bg-red-50 p-2 text-center text-xs">
                All rights reserved
            </footer>
        </body>
        </html>
    )
}

export default RootLayout